rethrow_database_error: protect against large buffers (#916)
* rethrow_database_error: protect against large buffers

Co-authored-by: Robert Norberg <132476312+robert-norberg@users.noreply.github.com>

* Add missing NEWS bullets

* Update R/utils.R

Co-authored-by: Simon P. Couch <simonpatrickcouch@gmail.com>

* Update tests/testthat/test-utils.R

Co-authored-by: Simon P. Couch <simonpatrickcouch@gmail.com>

---------

Co-authored-by: Robert Norberg <132476312+robert-norberg@users.noreply.github.com>
Co-authored-by: Simon P. Couch <simonpatrickcouch@gmail.com>